"use client";
import { useState, type ChangeEvent } from "react";
import { Archive, Download, ExternalLink, Plus, Search, Star, Trash2, Upload, Library } from "lucide-react";
import { toast } from "sonner";
import { CopyButton } from "@/components/shared/CopyButton";
import { useLocalStorage } from "@/hooks/useLocalStorage";
import type { PlannerTask } from "@/lib/career-planner";
import { LOCAL_STORAGE_KEYS } from "@/lib/constants";
import { downloadCsv, downloadJson } from "@/lib/export-utils";
import { QUESTION_CATEGORIES, QUESTION_STATUSES, averageQuestionConfidence, createQuestionBankItem, isQuestionReviewDue, lowestConfidenceQuestion, mergeQuestionBank, nextQuestionReview, questionBankText, questionCategoryCounts, questionStatusCounts, questionTagCounts, sortQuestionBank, type QuestionBankItem, type QuestionCategory, type QuestionStatus } from "@/lib/question-bank";

export default function QuestionBankPage() {
  const [items, setItems] = useLocalStorage<QuestionBankItem[]>(LOCAL_STORAGE_KEYS.interviewQuestionBank, []);
  const [plannerTasks, setPlannerTasks] = useLocalStorage<PlannerTask[]>(LOCAL_STORAGE_KEYS.plannerTasks, []);
  const [question, setQuestion] = useState(""); const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState<QuestionCategory | "all">("all"); const [statusFilter, setStatusFilter] = useState<QuestionStatus | "all">("all"); const [showArchived, setShowArchived] = useState(false);
  const visibleItems = sortQuestionBank(items).filter((item) => { if (!showArchived && item.status === "archived") return false; if (categoryFilter !== "all" && item.category !== categoryFilter) return false; if (statusFilter !== "all" && item.status !== statusFilter) return false; const query = search.trim().toLowerCase(); return !query || `${item.question} ${item.targetRole} ${item.company} ${item.answerOutline} ${item.sampleAnswer} ${item.keyPoints.join(" ")} ${item.tags.join(" ")} ${item.notes}`.toLowerCase().includes(query); });
  const categoryRows = Object.entries(questionCategoryCounts(visibleItems)); const statusRows = Object.entries(questionStatusCounts(visibleItems)); const tagRows = Object.entries(questionTagCounts(visibleItems)).sort((a, b) => b[1] - a[1]);
  const nextReview = nextQuestionReview(items);
  const weakestQuestion = lowestConfidenceQuestion(items);
  function addItem() { if (!question.trim()) return; setItems((current) => [createQuestionBankItem(question), ...current]); setQuestion(""); toast.success("Interview question added"); }
  function updateItem(id: string, patch: Partial<QuestionBankItem>) { setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item)); }
  function removeItem(id: string) { setItems((current) => current.filter((item) => item.id !== id)); toast.success("Question deleted"); }
  function duplicateItem(item: QuestionBankItem) { const now = new Date().toISOString(); setItems((current) => [{ ...item, id: crypto.randomUUID(), question: `${item.question} copy`, createdAt: now, updatedAt: now }, ...current]); toast.success("Question duplicated"); }
  function markPracticed(item: QuestionBankItem) { const today = new Date(); const next = new Date(today); next.setDate(today.getDate() + (item.confidence >= 8 ? 14 : item.confidence >= 6 ? 7 : 3)); updateItem(item.id, { practiceCount: item.practiceCount + 1, lastPracticedAt: today.toISOString().slice(0, 10), nextReviewAt: next.toISOString().slice(0, 10), status: item.confidence >= 8 ? "ready" : "practicing" }); toast.success("Practice recorded"); }
  function addToPlanner(item: QuestionBankItem) { const task: PlannerTask = { id: crypto.randomUUID(), title: `Practice: ${item.question}`, notes: `From interview question bank.${item.answerOutline ? ` Outline: ${item.answerOutline}` : ""}`, priority: isQuestionReviewDue(item) ? "high" : "medium", category: "interview", estimateMinutes: 30, resourceUrl: item.sourceUrl, status: "todo", dueDate: item.nextReviewAt, createdAt: new Date().toISOString(), completedAt: null, archived: false, tags: ["question-bank", ...item.tags.slice(0, 5)], recurrence: "none" }; setPlannerTasks([task, ...plannerTasks]); toast.success("Practice added to planner"); }
  async function importItems(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { const parsed = JSON.parse(await file.text()) as { questions?: QuestionBankItem[] } | QuestionBankItem[]; const incoming = Array.isArray(parsed) ? parsed : parsed.questions || []; setItems((current) => mergeQuestionBank(current, incoming)); toast.success(`${incoming.length} questions imported`); } catch { toast.error("Could not import questions"); } }
  return <div className="max-w-6xl space-y-6">
    <div><h2 className="text-xl font-semibold text-white">Interview Question Bank</h2><p className="mt-1 text-sm text-gray-400">Build, rehearse, and revisit answers before the interview clock starts.</p></div>
    {weakestQuestion && <div className="rounded-lg border border-amber-800/50 bg-amber-950/20 p-4 text-sm text-amber-100">Focus answer: <span className="font-semibold">{weakestQuestion.question}</span> at confidence {weakestQuestion.confidence}/10.</div>}
    {nextReview && <div className="rounded-lg border border-blue-800/50 bg-blue-950/20 p-4 text-sm text-blue-100">Next review: <span className="font-semibold">{nextReview.question}</span> on {nextReview.nextReviewAt}.</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[["Active", items.filter((item) => item.status !== "archived").length], ["Ready", items.filter((item) => item.status === "ready").length], ["Reviews due", items.filter((item) => isQuestionReviewDue(item)).length], ["Practice reps", items.reduce((sum, item) => sum + item.practiceCount, 0)], ["Avg confidence", `${averageQuestionConfidence(items)}/10`]].map(([label, value]) => <div key={label} className="rounded-lg border border-gray-800 bg-gray-900 p-4"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-xl font-bold text-white">{value}</div></div>)}</div>
    <div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><div className="flex gap-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addItem(); }} placeholder="Add an interview question" className="min-w-0 flex-1 rounded-lg border border-gray-700 bg-gray-800 px-4 py-2.5 text-sm text-white" /><button onClick={addItem} disabled={!question.trim()} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Plus className="h-4 w-4" />Add</button></div></div>
    <div className="flex flex-wrap gap-2"><select value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value as QuestionCategory | "all")} className="rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 text-sm text-gray-300"><option value="all">All categories</option>{QUESTION_CATEGORIES.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as QuestionStatus | "all")} className="rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 text-sm text-gray-300"><option value="all">All statuses</option>{QUESTION_STATUSES.filter((option) => option.value !== "archived").map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-600" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search questions, roles, answers, or tags" className="w-full rounded-lg border border-gray-700 bg-gray-900 py-2.5 pl-9 pr-3 text-sm text-white" /></label><button onClick={() => setShowArchived((value) => !value)} className="rounded-lg border border-gray-700 px-3 text-sm text-gray-300">Archived</button><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-gray-700 px-3 text-sm text-gray-300"><Upload className="h-4 w-4" />Import<input type="file" accept=".json" onChange={importItems} className="sr-only" /></label><CopyButton value={questionBankText(visibleItems) || "No questions yet"} label="Copy bank" /><button onClick={() => downloadJson("careerpilot-question-bank.json", { questions: items })} className="inline-flex items-center gap-2 rounded-lg border border-gray-700 px-3 text-sm text-gray-300"><Download className="h-4 w-4" />JSON</button><button onClick={() => downloadCsv("careerpilot-question-bank.csv", visibleItems.map((item) => ({ question: item.question, category: item.category, status: item.status, role: item.targetRole, company: item.company, confidence: item.confidence, difficulty: item.difficulty, practice_count: item.practiceCount, next_review: item.nextReviewAt, tags: item.tags.join(", ") })))} className="rounded-lg border border-gray-700 px-3 text-sm text-gray-300">CSV</button></div>
    {visibleItems.length === 0 ? <div className="rounded-lg border border-dashed border-gray-700 py-14 text-center"><Library className="mx-auto h-8 w-8 text-gray-600" /><p className="mt-3 text-sm text-gray-400">No questions match this view.</p></div> : <div className="space-y-4">{visibleItems.map((item) => <article key={item.id} className="rounded-lg border border-gray-800 bg-gray-900 p-5"><div className="flex gap-2"><button onClick={() => updateItem(item.id, { favorite: !item.favorite })} className={item.favorite ? "text-amber-400" : "text-gray-600"}><Star className="h-4 w-4" fill={item.favorite ? "currentColor" : "none"} /></button><textarea rows={2} value={item.question} onChange={(event) => updateItem(item.id, { question: event.target.value })} className="min-w-0 flex-1 resize-none bg-transparent text-lg font-semibold text-white outline-none" /><button onClick={() => duplicateItem(item)} className="text-xs text-gray-400">Duplicate</button><button onClick={() => updateItem(item.id, { status: "archived" })} className="p-2 text-gray-400"><Archive className="h-4 w-4" /></button><button onClick={() => removeItem(item.id)} className="p-2 text-gray-500"><Trash2 className="h-4 w-4" /></button></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-gray-500">Category<select value={item.category} onChange={(event) => updateItem(item.id, { category: event.target.value as QuestionCategory })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white">{QUESTION_CATEGORIES.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="text-xs text-gray-500">Status<select value={item.status} onChange={(event) => updateItem(item.id, { status: event.target.value as QuestionStatus })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white">{QUESTION_STATUSES.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="text-xs text-gray-500">Target role<input value={item.targetRole} onChange={(event) => updateItem(item.id, { targetRole: event.target.value })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Company<input value={item.company} onChange={(event) => updateItem(item.id, { company: event.target.value })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label></div>
      <div className="mt-3 grid gap-3 lg:grid-cols-2"><label className="text-xs text-gray-500">Answer outline<textarea rows={4} value={item.answerOutline} onChange={(event) => updateItem(item.id, { answerOutline: event.target.value })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Sample answer<textarea rows={4} value={item.sampleAnswer} onChange={(event) => updateItem(item.id, { sampleAnswer: event.target.value })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Key points<input value={item.keyPoints.join(", ")} onChange={(event) => updateItem(item.id, { keyPoints: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Tags<input value={item.tags.join(", ")} onChange={(event) => updateItem(item.id, { tags: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Next review<input type="date" value={item.nextReviewAt} onChange={(event) => updateItem(item.id, { nextReviewAt: event.target.value })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Source URL<input type="url" value={item.sourceUrl} onChange={(event) => updateItem(item.id, { sourceUrl: event.target.value })} className="mt-1 w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label></div>
      <div className="mt-4 flex flex-wrap items-center gap-4 border-t border-gray-800 pt-4"><label className="text-xs text-gray-500">Confidence <input type="range" min="1" max="10" value={item.confidence} onChange={(event) => updateItem(item.id, { confidence: Number(event.target.value) })} /><span className="text-white"> {item.confidence}/10</span></label><label className="text-xs text-gray-500">Difficulty <input type="range" min="1" max="10" value={item.difficulty} onChange={(event) => updateItem(item.id, { difficulty: Number(event.target.value) })} /><span className="text-white"> {item.difficulty}/10</span></label>{isQuestionReviewDue(item) && <span className="rounded-full bg-amber-950 px-2.5 py-1 text-xs text-amber-300">Review due</span>}{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noreferrer" className="text-gray-400"><ExternalLink className="h-4 w-4" /></a>}<button onClick={() => markPracticed(item)} className="ml-auto rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-300">Mark practiced</button><button onClick={() => addToPlanner(item)} className="rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-300">Add to planner</button></div></article>)}</div>}
    {(categoryRows.some(([, count]) => count) || statusRows.some(([, count]) => count) || tagRows.length > 0) && <div className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><h3 className="text-sm font-semibold text-white">Categories</h3>{categoryRows.filter(([, count]) => count).map(([key, count]) => <div key={key} className="mt-2 flex justify-between text-sm text-gray-400"><span>{QUESTION_CATEGORIES.find((option) => option.value === key)?.label}</span><span>{count}</span></div>)}</div><div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><h3 className="text-sm font-semibold text-white">Readiness</h3>{statusRows.filter(([, count]) => count).map(([key, count]) => <div key={key} className="mt-2 flex justify-between text-sm text-gray-400"><span>{QUESTION_STATUSES.find((option) => option.value === key)?.label}</span><span>{count}</span></div>)}</div><div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><h3 className="text-sm font-semibold text-white">Themes</h3><div className="mt-3 flex flex-wrap gap-2">{tagRows.slice(0, 12).map(([tag, count]) => <span key={tag} className="rounded-full bg-gray-800 px-2.5 py-1 text-xs text-gray-300">{tag} · {count}</span>)}</div></div></div>}
  </div>;
}
