"use client";

import { useState, type ChangeEvent } from "react";
import { Archive, Download, ExternalLink, Plus, Search, Star, Trash2, Upload, UserCheck } from "lucide-react";
import { toast } from "sonner";
import { CopyButton } from "@/components/shared/CopyButton";
import { useLocalStorage } from "@/hooks/useLocalStorage";
import type { PlannerTask } from "@/lib/career-planner";
import { LOCAL_STORAGE_KEYS } from "@/lib/constants";
import { downloadCsv, downloadJson } from "@/lib/export-utils";
import {
  REFERENCE_RELATIONSHIPS, REFERENCE_STATUSES, createProfessionalReference, isReferenceActionDue, isReferenceActionSoon,
  confirmedReferenceCount, mergeProfessionalReferences, nextReferenceAction, recentlyUsedReferenceCount, referenceAverageConfidence, referencePlanText, referenceRelationshipCounts, referenceThankYouDueCount,
  referenceStatusCounts, referenceStrengthCounts, sortProfessionalReferences, type ProfessionalReference,
  type ReferenceRelationship, type ReferenceStatus,
} from "@/lib/professional-references";

export default function ReferencesPage() {
  const [references, setReferences] = useLocalStorage<ProfessionalReference[]>(LOCAL_STORAGE_KEYS.professionalReferences, []);
  const [plannerTasks, setPlannerTasks] = useLocalStorage<PlannerTask[]>(LOCAL_STORAGE_KEYS.plannerTasks, []);
  const [name, setName] = useState("");
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<ReferenceStatus | "all">("all");
  const [relationshipFilter, setRelationshipFilter] = useState<ReferenceRelationship | "all">("all");
  const [showArchived, setShowArchived] = useState(false);
  const visibleReferences = sortProfessionalReferences(references).filter((reference) => {
    if (!showArchived && reference.status === "archived") return false;
    if (statusFilter !== "all" && reference.status !== statusFilter) return false;
    if (relationshipFilter !== "all" && reference.relationship !== relationshipFilter) return false;
    const query = search.trim().toLowerCase();
    return !query || `${reference.name} ${reference.title} ${reference.company} ${reference.email} ${reference.workedTogether} ${reference.supportingStories} ${reference.notes} ${reference.strengths.join(" ")}`.toLowerCase().includes(query);
  });
  const statusRows = Object.entries(referenceStatusCounts(visibleReferences));
  const relationshipRows = Object.entries(referenceRelationshipCounts(visibleReferences));
  const strengthRows = Object.entries(referenceStrengthCounts(visibleReferences)).sort((a, b) => b[1] - a[1]);
  const nextAction = nextReferenceAction(references);

  function addReference() { if (!name.trim()) return; setReferences((current) => [createProfessionalReference(name), ...current]); setName(""); toast.success("Professional reference added"); }
  function updateReference(id: string, patch: Partial<ProfessionalReference>) { setReferences((current) => current.map((reference) => reference.id === id ? { ...reference, ...patch, updatedAt: new Date().toISOString() } : reference)); }
  function removeReference(id: string) { setReferences((current) => current.filter((reference) => reference.id !== id)); toast.success("Reference deleted"); }
  function duplicateReference(reference: ProfessionalReference) { const now = new Date().toISOString(); setReferences((current) => [{ ...reference, id: crypto.randomUUID(), name: `${reference.name} copy`, createdAt: now, updatedAt: now }, ...current]); toast.success("Reference duplicated"); }
  function addToPlanner(reference: ProfessionalReference) {
    const task: PlannerTask = { id: crypto.randomUUID(), title: reference.nextAction || `Contact ${reference.name}`, notes: `Created from professional references.${reference.supportingStories ? ` Context: ${reference.supportingStories}` : ""}`, priority: isReferenceActionDue(reference) ? "high" : "medium", category: "networking", estimateMinutes: 20, resourceUrl: reference.linkedInUrl, status: "todo", dueDate: reference.nextActionDate, createdAt: new Date().toISOString(), completedAt: null, archived: false, tags: ["reference", ...reference.strengths.slice(0, 5)], recurrence: "none" };
    setPlannerTasks([task, ...plannerTasks]); toast.success("Reference action added to planner");
  }
  async function importReferences(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; event.target.value = ""; if (!file) return;
    try { const parsed = JSON.parse(await file.text()) as { references?: ProfessionalReference[] } | ProfessionalReference[]; const incoming = Array.isArray(parsed) ? parsed : parsed.references || []; setReferences((current) => mergeProfessionalReferences(current, incoming)); toast.success(`${incoming.length} references imported`); } catch { toast.error("Could not import references"); }
  }
  function resetFilters() { setSearch(""); setStatusFilter("all"); setRelationshipFilter("all"); setShowArchived(false); }

  return <div className="max-w-6xl space-y-6">
    <div><h2 className="text-xl font-semibold text-white">Professional References</h2><p className="mt-1 text-sm text-gray-400">Prepare trusted advocates before an employer asks for them.</p></div>
    {nextAction && <div className="rounded-lg border border-blue-800/50 bg-blue-950/20 p-4 text-sm text-blue-100">Next reference action: <span className="font-semibold">{nextAction.action}</span> for {nextAction.name} by {nextAction.date}.</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-7">{[
      ["Active", references.filter((reference) => reference.status !== "archived").length],
      ["Confirmed", confirmedReferenceCount(references)],
      ["Recently used", recentlyUsedReferenceCount(references)],
      ["Thank-yous due", referenceThankYouDueCount(references)],
      ["Permission pending", references.filter((reference) => reference.status === "permission_requested").length],
      ["Actions due", references.filter((reference) => isReferenceActionDue(reference)).length],
      ["Avg confidence", `${referenceAverageConfidence(references)}/10`],
    ].map(([label, value]) => <div key={label} className="rounded-lg border border-gray-800 bg-gray-900 p-4"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-xl font-bold text-white">{value}</div></div>)}</div>

    <div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><div className="flex gap-2"><input value={name} maxLength={140} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") addReference(); }} placeholder="Add a manager, colleague, client, or mentor" className="min-w-0 flex-1 rounded-lg border border-gray-700 bg-gray-800 px-4 py-2.5 text-sm text-white outline-none focus:border-blue-500" /><button onClick={addReference} disabled={!name.trim()} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Plus className="h-4 w-4" />Add</button></div></div>

    <div className="flex flex-wrap gap-2">
      <select aria-label="Filter references by status" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as ReferenceStatus | "all")} className="rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 text-sm text-gray-300"><option value="all">All statuses</option>{REFERENCE_STATUSES.filter((item) => item.value !== "archived").map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>
      <select aria-label="Filter references by relationship" value={relationshipFilter} onChange={(event) => setRelationshipFilter(event.target.value as ReferenceRelationship | "all")} className="rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 text-sm text-gray-300"><option value="all">All relationships</option>{REFERENCE_RELATIONSHIPS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>
      <label className="relative min-w-64 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-600" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search references, context, stories, or strengths" className="w-full rounded-lg border border-gray-700 bg-gray-900 py-2.5 pl-9 pr-3 text-sm text-white outline-none focus:border-blue-500" /></label>
      <button onClick={() => setShowArchived((value) => !value)} aria-pressed={showArchived} className="rounded-lg border border-gray-700 px-3 text-sm text-gray-300">Archived</button><button onClick={resetFilters} className="rounded-lg border border-gray-700 px-3 text-sm text-gray-300">Reset</button>
      <label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-gray-700 px-3 text-sm text-gray-300"><Upload className="h-4 w-4" />Import<input type="file" accept=".json,application/json" onChange={importReferences} className="sr-only" /></label>
      <CopyButton value={referencePlanText(visibleReferences) || "No references yet"} label="Copy brief" className="rounded-lg px-3" />
      <button onClick={() => downloadJson("careerpilot-professional-references.json", { references })} className="inline-flex items-center gap-2 rounded-lg border border-gray-700 px-3 text-sm text-gray-300"><Download className="h-4 w-4" />JSON</button>
      <button onClick={() => downloadCsv("careerpilot-professional-references.csv", visibleReferences.map((reference) => ({ name: reference.name, title: reference.title, company: reference.company, relationship: reference.relationship, status: reference.status, email: reference.email, phone: reference.phone, preferred_contact: reference.preferredContact, confidence: reference.confidence, strengths: reference.strengths.join(", "), next_action: reference.nextAction, next_action_date: reference.nextActionDate })))} className="inline-flex items-center gap-2 rounded-lg border border-gray-700 px-3 text-sm text-gray-300"><Download className="h-4 w-4" />CSV</button>
    </div>

    {visibleReferences.length === 0 ? <div className="rounded-lg border border-dashed border-gray-700 py-14 text-center"><UserCheck className="mx-auto h-8 w-8 text-gray-600" /><p className="mt-3 text-sm text-gray-400">No references match this view.</p></div> : <div className="space-y-4">{visibleReferences.map((reference) => <article key={reference.id} className="rounded-lg border border-gray-800 bg-gray-900 p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 flex-1 items-center gap-2"><button onClick={() => updateReference(reference.id, { favorite: !reference.favorite })} title={reference.favorite ? "Remove favorite" : "Favorite reference"} className={reference.favorite ? "text-amber-400" : "text-gray-600"}><Star className="h-4 w-4" fill={reference.favorite ? "currentColor" : "none"} /></button><input value={reference.name} onChange={(event) => updateReference(reference.id, { name: event.target.value })} className="min-w-0 flex-1 bg-transparent text-lg font-semibold text-white outline-none" /></div><div className="flex items-center gap-2">{reference.linkedInUrl && <a href={reference.linkedInUrl} target="_blank" rel="noreferrer" title="Open LinkedIn profile" className="rounded-md p-2 text-gray-400 hover:bg-gray-800"><ExternalLink className="h-4 w-4" /></a>}<button onClick={() => duplicateReference(reference)} className="rounded-md px-2 py-1.5 text-xs text-gray-400">Duplicate</button><button onClick={() => updateReference(reference.id, { status: "archived" })} title="Archive" className="rounded-md p-2 text-gray-400"><Archive className="h-4 w-4" /></button><button onClick={() => removeReference(reference.id)} title="Delete" className="rounded-md p-2 text-gray-500 hover:text-red-300"><Trash2 className="h-4 w-4" /></button></div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-xs text-gray-500">Status<select value={reference.status} onChange={(event) => updateReference(reference.id, { status: event.target.value as ReferenceStatus })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white">{REFERENCE_STATUSES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label className="text-xs text-gray-500">Relationship<select value={reference.relationship} onChange={(event) => updateReference(reference.id, { relationship: event.target.value as ReferenceRelationship })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white">{REFERENCE_RELATIONSHIPS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
        <label className="text-xs text-gray-500">Title<input value={reference.title} onChange={(event) => updateReference(reference.id, { title: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Company<input value={reference.company} onChange={(event) => updateReference(reference.id, { company: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label>
        <label className="text-xs text-gray-500">Email<input type="email" value={reference.email} onChange={(event) => updateReference(reference.id, { email: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Phone<input type="tel" value={reference.phone} onChange={(event) => updateReference(reference.id, { phone: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label>
        <label className="text-xs text-gray-500">Preferred contact<select value={reference.preferredContact} onChange={(event) => updateReference(reference.id, { preferredContact: event.target.value as ProfessionalReference["preferredContact"] })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white"><option value="email">Email</option><option value="phone">Phone</option><option value="linkedin">LinkedIn</option></select></label><label className="text-xs text-gray-500">Next action date<input type="date" value={reference.nextActionDate} onChange={(event) => updateReference(reference.id, { nextActionDate: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label>
      </div>
      <div className="mt-3 grid gap-3 lg:grid-cols-2"><label className="text-xs text-gray-500">LinkedIn URL<input type="url" value={reference.linkedInUrl} onChange={(event) => updateReference(reference.id, { linkedInUrl: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Worked together<input value={reference.workedTogether} onChange={(event) => updateReference(reference.id, { workedTogether: event.target.value })} placeholder="Team, project, and dates" className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Next action<input value={reference.nextAction} onChange={(event) => updateReference(reference.id, { nextAction: event.target.value })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Strengths they can validate<input value={reference.strengths.join(", ")} onChange={(event) => updateReference(reference.id, { strengths: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} className="mt-1 block w-full rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Supporting stories<textarea rows={3} value={reference.supportingStories} onChange={(event) => updateReference(reference.id, { supportingStories: event.target.value })} className="mt-1 block w-full resize-y rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-gray-500">Notes<textarea rows={3} value={reference.notes} onChange={(event) => updateReference(reference.id, { notes: event.target.value })} className="mt-1 block w-full resize-y rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-sm text-white" /></label></div>
      <div className="mt-4 flex flex-wrap items-center gap-4 border-t border-gray-800 pt-4"><label className="text-xs text-gray-500">Confidence <input type="range" min="1" max="10" value={reference.confidence} onChange={(event) => updateReference(reference.id, { confidence: Number(event.target.value) })} className="mx-2 align-middle" /><span className="text-white">{reference.confidence}/10</span></label><label className="inline-flex items-center gap-2 text-xs text-gray-400"><input type="checkbox" checked={reference.thankYouSent} onChange={(event) => updateReference(reference.id, { thankYouSent: event.target.checked })} />Thank-you sent</label>{isReferenceActionDue(reference) && <span className="rounded-full bg-amber-950 px-2.5 py-1 text-xs text-amber-300">Action due</span>}{!isReferenceActionDue(reference) && isReferenceActionSoon(reference) && <span className="rounded-full bg-blue-950 px-2.5 py-1 text-xs text-blue-300">Due this week</span>}<button onClick={() => addToPlanner(reference)} className="ml-auto rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-300">Add to planner</button></div>
    </article>)}</div>}
    {(statusRows.some(([, count]) => count > 0) || relationshipRows.some(([, count]) => count > 0) || strengthRows.length > 0) && <div className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><h3 className="text-sm font-semibold text-white">Readiness</h3>{statusRows.filter(([, count]) => count > 0).map(([status, count]) => <div key={status} className="mt-2 flex justify-between text-sm text-gray-400"><span>{REFERENCE_STATUSES.find((item) => item.value === status)?.label}</span><span>{count}</span></div>)}</div><div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><h3 className="text-sm font-semibold text-white">Relationship mix</h3>{relationshipRows.filter(([, count]) => count > 0).map(([relationship, count]) => <div key={relationship} className="mt-2 flex justify-between text-sm text-gray-400"><span>{REFERENCE_RELATIONSHIPS.find((item) => item.value === relationship)?.label}</span><span>{count}</span></div>)}</div><div className="rounded-lg border border-gray-800 bg-gray-900 p-5"><h3 className="text-sm font-semibold text-white">Strength coverage</h3><div className="mt-3 flex flex-wrap gap-2">{strengthRows.slice(0, 12).map(([strength, count]) => <span key={strength} className="rounded-full bg-gray-800 px-2.5 py-1 text-xs text-gray-300">{strength} · {count}</span>)}</div></div></div>}
  </div>;
}
